version: '3'
services:
  blastservice:
    container_name: orfanid-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8085"
    volumes:
      - /home/ubuntu/apps/out:/dataoutputdir
#      - /home/vinodh/out:/dataoutputdir
#      - /Users/hewapathirana/projects/ORFanFinder/out:/dataoutputdir
