version: '3'
services:
  blastservice:
    container_name: orfanid-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8085"
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - /home/ubuntu/apps/out:/dataoutputdir
#      - /home/vinodh/out:/dataoutputdir
#      - /Users/hewapathirana/projects/ORFanFinder/out:/dataoutputdir
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/ubuntu/apps/rabbit/data:/var/lib/rabbitmq/
      - /home/ubuntu/apps/rabbit/log/:/var/log/rabbitmq

networks:
  default:
    external:
      name: orfanid

