version: '3'
services:
  blastservice:
    container_name: orfanid-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - /home/orfanid/out:/dataoutputdir
      - /home/orfanid/nr_db:/nr_db
      - /mnt/data/orfanid/orfanid/diamond_dir/nr_fasta:/diamond_nr_db
      - /home/orfanid/nt_db:/nt_db
      - /home/orfanid/new_taxdump:/new_taxdump
      - /home/orfanid/blast_bin/bin:/blast/bin
      - /home/orfanid/diamond_dir/bin:/diamond/bin
#      - /home/vinodh/out:/dataoutputdir
#      - /Users/hewapathirana/projects/ORFanFinder/out:/dataoutputdir
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /mnt/data/orfanid/orfanid/rabbitmq_data/data:/var/lib/rabbitmq/
      - /mnt/data/orfanid/orfanid/rabbitmq_data/log/:/var/log/rabbitmq

networks:
  default:
    external:
      name: orfanid

