version: "3"
services:
  blastservice:
    container_name: orfanid-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - rabbitmq
    volumes:
      - /home/orfanid/out:/dataoutputdir
      - /home/orfanid/nr_db_new:/nr_db
      - /home/orfanid/diamond_dir/nr_fasta:/diamond_nr_db
      - /home/orfanid/nt_db_new:/nt_db
      - /home/orfanid/new_taxdump:/new_taxdump
      - /home/orfanid/blast_bin/bin:/blast/bin
      - /home/orfanid/diamond_dir/bin:/diamond/bin
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /home/orfanid/rabbitmq_data/data:/var/lib/rabbitmq/
      - /home/orfanid/rabbitmq_data/log/:/var/log/rabbitmq
    restart: unless-stopped

networks:
  default:
    external:
      name: orfanid
