# PROFILES
spring:
  profiles:
    active: "unix"
  thymeleaf:
        cache: false
#-Dspring.profiles.active=unix

server:
  error:
    path: /error
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: DEBUG

---

spring:
  profiles: unix

server:
  port: 8085

data.outputdir: /Users/hewapathirana/projects/ORFanFinder/unix/out/
ncbi.blast.programme.location: /usr/local/ncbi/blast/bin/

---

spring:
  profiles: windows

server:
  port: 8086

data.outputdir: C:\\Users\\vinod\\OneDrive\\Documents\\Discovery Institute\\2020\\ORFanID-master\\output\\
ncbi.blast.programme.location: C:\\Program Files\\NCBI\\blast-2.6.0+\\bin\\
