spring.application.name: ORFanID

# PROFILES
spring:
  profiles:
    active: "unix"
  thymeleaf:
        cache: false

server:
  error:
    path: /error
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: INFO

---

spring:
  profiles: unix

server:
  port: 8085

data.outputdir: /Users/hewapathirana/projects/ORFanFinder/out
ncbi.blast.programme.location: /usr/local/ncbi/blast/bin/
app.dir.root: /app/

db.api:
  baseUrl: http://localhost:8081
  keyName: x-api-key
  keyValue: Janaya

