# PROFILES
spring:
  profiles:
    active: "unix"
  thymeleaf:
        cache: false

server:
  error:
    path: /error
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: INFO

---

spring:
  profiles: unix

server:
  port: 8085

data.outputdir: /dataoutputdir/
ncbi.blast.programme.location: /usr/local/ncbi/blast/bin/
app.dir.root: /app/

